### ISSUE TITLE
Location tab crashes the app (Android)

### ISSUE THREAD

**Issue by edern-appere** [SimpleAppProjects/SimpleWeather-Android#1]
Hi there,

I'm running version 3.3.1 of the app on my smartphone (Oneplus 6T with LineageOs 17.1). Since the release of v3.3.1, whenever I try to open the Locations tab, the app keeps trying to fetch data and then crashes. I tried to change the weather provider from the default one (Here) to another one (Yahoo) but it doesn't change anything. 
If you need further details I can try to provide them (but I'm no developer).

Apart from this issue the app is really great : lots of useful features, slick interface and small footprint. Congrats !

Have a nice day

Best regards,

**Comment by thewizrd** [comment]
Hi,

Thanks for reporting this issue. Does the app crash as soon as you click on the 'Locations' tab or after performing an action like deleting or clicking on a location?

**Comment by edern-appere** [comment]
When I hit the location tab, it highlights with a big white background circle, the app seems to try to load something but nothing appears, it freezes and after a while (one minute),  Android askes me to kill it because it's unresponsive.
I cannot see any location in the list. 
I tried to uninstall the app and reinstall it but it doesn't change anything.

**Comment by thewizrd** [comment]
Could you test the next update here (https://play.google.com/apps/testing/com.thewizrd.simpleweather) to see if it makes a difference?

**Comment by edern-appere** [comment]
I'm sorry but I don't have direct access to the play store so I cannot download the update :-/

**Comment by edern-appere** [comment]
Latest version of the app works perfectly out of the box. This issue can now be closed.
