### ISSUE TITLE
Feature Request: Combined Sunrise/Sunset and Moon Phase (and extra data) tile on Wear OS

### ISSUE THREAD

**Issue by Dondrejohnson5** [SimpleAppProjects/SimpleWeather-Android#14]
I would love to see an extra tile on Wear OS that is customizable: allowing us to enable disable showing of extra data on a single tile, such as: Sunrise/sunset, Moon Phase (primarily these two), Moonrise/moonset, AQI, Beaufort, etc, and others that would not otherwise be shown on the other four Weather tiles of the app.

Watch: Google Pixel Watch 3 LTE (45mm)
Wear OS version: 5
Watch app version: 5.10.0
Phone: Motorola Edge 40 Pro
Phone Android version: 14
Phone app version: 5.10.0

**Comment by thewizrd** [comment]
Feature will be added in the next release:

https://github.com/SimpleAppProjects/SimpleWeather-Android/commit/68833516fb55e0302b404eb9645612aa34c22dd1

**Comment by Dondrejohnson5** [comment]
Thank you, although I didn't get to see Moon Phase as one of the options in the new tile, which I was hoping for
