### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by adolfomoro** [SimpleAppProjects/SimpleWeather-Android#2]
Code for close Tile ? (back to clock "Home Screen")

**Comment by thewizrd** [comment]
> Code for close Tile ? (back to clock "Home Screen")

Hi, I'm not sure about which tile your mentioning? The code for all of the wearable tiles can be found [HERE](https://github.com/SimpleAppProjects/SimpleWeather-Android/tree/master/wearapp/src/main/java/com/thewizrd/simpleweather/wearable)
