### ISSUE TITLE
Design of a new application icon

### ISSUE THREAD

**Issue by amoledwatchfaces** [SimpleAppProjects/SimpleWeather-Android#3]
I've re-created your app icon. Now it goes well with dark/light android themes. What do you think ?

![simpleweather](https://user-images.githubusercontent.com/92080649/150630640-38f59e81-3934-49dc-bd5e-5b4e46f066af.png)

**Comment by amoledwatchfaces** [comment]
![scr1](https://user-images.githubusercontent.com/92080649/150630867-3c91c835-7368-4e4a-a682-c7acffd67dae.png)
![scr2](https://user-images.githubusercontent.com/92080649/150630877-f4e632f2-a07e-4086-91ff-aa2a61e44759.png)

**Comment by thewizrd** [comment]
thx again for this
